jetstack/test-infra

prow/plugins.yaml

This will require webhooks setting up on the navigator repository
/cc @simonswine

Add prow configuration for navigator

---

mungegithub/cherrypick/deployment/tarmak/Makefile
mungegithub/cherrypick/deployment/tarmak/configmap.yaml
mungegithub/cherrypick/ingress.yaml

Add tarmak cherrypick config

---

jobs/config.json

Reverts jetstack/test-infra#28

Revert "Update commands to run puppet unit tests"

---

images/ruby-2.3/Dockerfile
images/ruby-2.3/Makefile
jobs/config.json
prow/cluster/plank_deployment.yaml
prow/config.yaml

@munnerz this adds vagrant/virtual box to the ruby image and updates plank to run on the hetzner box..

Puppet acceptance tests

---

prow/config.yaml

This runs vagrant/virtualbox with elevated privileges and trails anchors in the yaml

Enable virtualbox containers to run

---

prow/config.yaml

Set initial presubmit resource requests

---

prow/config.yaml

Set privileged=true for minikube jobs

---

prow/config.yaml

Resize build pod requests

---

prow/config.yaml

This should help expose test flakes

Add navigator e2e periodics

---

prow/config.yaml

Fix puppet-module-tarmak-acceptance-1-8-centos regex

---

prow/config.yaml

Fix tarmak regex trigger rules

---

prow/config.yaml

Old vs new regex: https://play.golang.org/p/cpZwc6urC2
/cc @wallrj @simonswine

Fix navigator e2e test regex

---

prow/config.yaml

Adds cheap submit queue using prow for puppet modules tarmak and kubernets

---

mungegithub/submit-queue/deployment/tarmak/configmap.yaml

Require tarmak-quick-verify instead of travis build

---

prow/config.yaml

Update presubmit regex to match mungegithub trigger

---

prow/config.yaml

Update CPU resource requests

---

jobs/config.json
prow/config.yaml

Add an ubnutu vault_client acceptance test

---

images/gcloud/Dockerfile
images/gcloud/Makefile
prow/config.yaml

Install the helm binary in the quick-verify image

---

images/sphinx-docs/Dockerfile
images/sphinx-docs/Makefile
images/sphinx-docs/requirements.txt
images/sphinx-docs/runner
jobs/config.json
prow/config.yaml

can you give ti a quick sanity check @munnerz

Add prow tarmak docs

---

scenarios/minikube.py

Hopefully this will give kubelet logs for diagnosing test failures such as https://github.com/jetstack/navigator/pull/168#issuecomment-351103506 where a namespace failed to delete in time....possibly because a container wasn't stopped.

Print the minikube logs after each test run

---

gubernator/config.yaml

gubernator: Set default org to 'jetstack'

---

prow/config.yaml

Update navigator CPU requests

---

prow/config.yaml

Reverts jetstack/test-infra#105

Revert "Update Prow for minikube-in-go 0.4"

---

prow/config.yaml

Reverts jetstack/test-infra#104

Revert "Bump minikube in go images to 0.3"

---

images/minikube-in-go/Dockerfile
scenarios/minikube.py

Reverts jetstack/test-infra#101

Revert "Use the minikube in-tree kvm2 driver"

---

prow/config.yaml

Update tide config for new prow

Update tide config

---

images/minikube-in-go/Dockerfile
scenarios/minikube.py

Reverts jetstack/test-infra#108
Trying this again now we've sorted out some networking issues with test-infra

Revert "Revert "Use the minikube in-tree kvm2 driver""

---

prow/config.yaml

Reverts jetstack/test-infra#113

Revert "Bump minikube prow jobs"

---

images/minikube-in-go/Dockerfile
scenarios/minikube.py

Reverts jetstack/test-infra#112

Revert "Revert "Revert "Use the minikube in-tree kvm2 driver"""

---

experiment/needs-rebase/Dockerfile
prow/Makefile
prow/cluster/needs_rebase_deployment.yaml
prow/cluster/needs_rebase_service.yaml
prow/plugins.yaml

* Docker image build
* Manifests for the service
* Enable it for kube-lego
Already live and working, just want a second pair of eyes on it

Adds needs-rebase external plugin

---

images/minikube-in-go/Dockerfile
images/minikube-in-go/Makefile
prow/config.yaml

Add dep to minikube-in-go and bump Prow image version

---

prow/config.yaml

Revert minikube in go jobs to Helm 2.6.1

---

images/bazelbuild/Makefile
images/bazelbuild/runner
images/minikube-in-go/Dockerfile
images/minikube-in-go/Makefile
prow/config.yaml

This PR adds some initial bazel-based jobs for navigator unit & e2e tests.
Follow up PRs will clean this up and add additional jobs.

Add Bazel jobs for Navigator

---

jobs/config.json
prow/config.yaml

New default version to test is 1.8

Add tarmak module tests for 1.9, 1.10

---

jobs/config.json
prow/config.yaml

Run kubernetes tests on tarmak if puppet module for kubernetes has been
changed
/cc @munnerz

Test run_if_changed feature of plank

---

jobs/config.json
prow/config.yaml

/cc @munnerz 
gonna do a self merge :stuck_out_tongue_winking_eye:

Add puppet tarmak module test for main tarmak repo

---

images/gcloud/Dockerfile
images/gcloud/Makefile
images/minikube-in-go/Dockerfile
images/minikube-in-go/Makefile
prow/config.yaml

Resolves https://github.com/jetstack/cert-manager/issues/429

Upgrade helm to 2.8.2 in minikube-in-go and gcloud images

---

prow/config.yaml

/cc @munnerz This time with a PR :laughing:

Fix naming of triggers for vault_client/etcd

---

jobs/config.json
prow/config.yaml
prow/plugins.yaml

Add okta-kubectl-auth

---

prow/config.yaml

Enable automatic lifecycle periodics

---

config/jobs/test-infra/test-infra-presubmits.yaml

This is an attempt to get some form of config validation running on test-infra

Copy across test-infra presubmits

---

prow/cluster/hook_service.yaml
prow/cluster/lego_deployment.yaml
prow/cluster/plank_deployment.yaml
prow/cluster/pushgateway_deployment.yaml

This is already deployed like this

Add metric scrape annotations and disable kube-lego

---

config/jobs/cert-manager/cert-manager-periodics.yaml
config/jobs/cert-manager/cert-manager-presubmits.yaml

I think all this config is valid 🤞 
/cc @kragniz

Make cert-manager e2e jobs <k8s 1.9 non-blocking, and create periodics
